name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 21 * * *"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: install dependencies
        run: npm run install

      - name: build project
        run: npm run build
      
      - name: commit changes
        run: |
          git config --global user.name 'Aisen60'
          git config --global user.email 'caixusheng60@gmail.com'
          git pull --unshallow
          # 设置上游仓库
          # git remote add upstream https://github.com/Aisen60/vant-theme.git
          # git fetch upstream
          git add .
          git commit -m 'github actions ci: update source'
          git push origin main


      - name: deploy gh page
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GH_PAGES }}
          publish_dir: ./dist
