name: Sync to Gitee

on:
  workflow_dispatch:
  push:
    branches: [dev,website,gh-pages]
  schedule:
    - cron: "0 21 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # GitHub 源仓库地址
          source-repo: git@github.com:Aisen60/vant-theme.git
          # Gitee 目标仓库地址
          destination-repo: git@gitee.com:aisen60/vant-theme.git
      
      # 绕过手机验证码：https://github.com/yanglbme/gitee-pages-action/issues/6#issuecomment-664812675
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # Gitee 用户名
          gitee-username: ${{ secrets.GITEE_USERNAME }}
          # Gitee 密码
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # Gitee 仓库
          gitee-repo: Aisen60/vant-theme
          # 要部署的分支
          branch: gh-pages